import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const fmtMoney = (n: number | null | undefined, currency: string, locale: string) => {
  if (n === null || n === undefined || isNaN(Number(n))) return "—";
  try {
    return new Intl.NumberFormat(locale, { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(n));
  } catch {
    return `${currency} ${Number(n).toLocaleString()}`;
  }
};

const escapeHtml = (s: string) =>
  String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

interface Slide {
  title: string;
  bullets: string[];
  speaker_notes?: string;
}

const buildHtml = (opts: {
  ideaTitle: string;
  authorName: string;
  country: string;
  currency: string;
  income: string;
  slides: Slide[];
}) => {
  const slidesHtml = opts.slides
    .map(
      (s, i) => `
    <section class="slide">
      <div class="slide-inner">
        <div class="slide-num">${i + 1} / ${opts.slides.length}</div>
        <h2>${escapeHtml(s.title)}</h2>
        <ul>${s.bullets.map((b) => `<li>${escapeHtml(b)}</li>`).join("")}</ul>
        ${s.speaker_notes ? `<aside class="notes">${escapeHtml(s.speaker_notes)}</aside>` : ""}
      </div>
    </section>`
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>${escapeHtml(opts.ideaTitle)} — Business Plan</title>
<style>
  :root { --bg:#0b1230; --fg:#f3f5fb; --muted:#9aa3c7; --accent:#3b82f6; --emerald:#34d399; }
  *{box-sizing:border-box} html,body{margin:0;padding:0;background:var(--bg);color:var(--fg);font-family:'Plus Jakarta Sans','Inter',system-ui,sans-serif;line-height:1.5}
  header{padding:28px 36px;border-bottom:1px solid rgba(255,255,255,.08);display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:12px}
  header h1{margin:0;font-size:20px}
  header .meta{color:var(--muted);font-size:13px}
  main{max-width:980px;margin:0 auto;padding:24px}
  .slide{margin:24px 0;border-radius:18px;background:linear-gradient(135deg,rgba(59,130,246,.12),rgba(52,211,153,.06));border:1px solid rgba(255,255,255,.08);box-shadow:0 20px 50px -25px rgba(0,0,0,.7);overflow:hidden}
  .slide-inner{padding:42px 44px;min-height:340px;position:relative}
  .slide-num{position:absolute;top:18px;right:24px;color:var(--muted);font-size:12px;letter-spacing:.08em;text-transform:uppercase}
  .slide h2{margin:0 0 18px;font-size:30px;color:var(--fg);font-weight:800;letter-spacing:-.01em}
  .slide ul{padding-left:22px;margin:0;font-size:17px;color:#dde3f5}
  .slide li{margin:8px 0}
  .notes{margin-top:24px;padding:14px 16px;background:rgba(255,255,255,.04);border-left:3px solid var(--emerald);border-radius:8px;font-size:13px;color:var(--muted)}
  footer{text-align:center;padding:32px;color:var(--muted);font-size:12px}
  @media print { body{background:#fff;color:#000} .slide{page-break-after:always;background:#fff;border:none;box-shadow:none} .slide h2{color:#0b1230} .slide-num,.notes{color:#555} }
</style>
</head>
<body>
<header>
  <h1>🔥 ${escapeHtml(opts.ideaTitle)}</h1>
  <div class="meta">By ${escapeHtml(opts.authorName)} · ${escapeHtml(opts.country)} · Projected ${escapeHtml(opts.income)}/mo</div>
</header>
<main>${slidesHtml}</main>
<footer>Generated by Reignite AI · Press ⌘/Ctrl+P to export as PDF</footer>
</body>
</html>`;
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const PUB_KEY = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") || Deno.env.get("SUPABASE_ANON_KEY")!;
    const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const authedClient = createClient(SUPABASE_URL, PUB_KEY, {
      global: { headers: { Authorization: authHeader } },
    });
    const token = authHeader.replace(/^Bearer\s+/i, "");
    const { data: userData, error: authError } = await authedClient.auth.getUser(token);
    if (authError || !userData?.user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const user = userData.user;

    const { ideaId } = await req.json();
    if (!ideaId || typeof ideaId !== "string") {
      return new Response(JSON.stringify({ error: "ideaId is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Service-role client for storage upload + DB write (avoids RLS surprises on storage)
    const admin = createClient(SUPABASE_URL, SERVICE_KEY);

    const [ideaRes, profileRes] = await Promise.all([
      authedClient.from("business_ideas").select("*").eq("id", ideaId).eq("user_id", user.id).maybeSingle(),
      authedClient.from("profiles").select("*").eq("user_id", user.id).maybeSingle(),
    ]);

    const idea = ideaRes.data as any;
    if (!idea) {
      return new Response(JSON.stringify({ error: "Idea not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const profile = profileRes.data as any;
    const currency = profile?.currency || "USD";
    const locale = profile?.language || "en-US";
    const country = profile?.country || "Unknown";
    const incomeStr = fmtMoney(Number(idea.projected_monthly_income) || 0, currency, locale);

    // Ask Lovable AI for a structured 8-slide deck
    const sysPrompt = `You are a pitch-deck writer. Output a JSON object with key "slides" — an array of 8 slides. Each slide has: title (string), bullets (3-5 short strings), speaker_notes (1-2 sentence string). Cover: 1) Title/vision, 2) Problem, 3) Solution, 4) Target customer (in ${country}), 5) Revenue model & projected monthly income (${incomeStr}), 6) Go-to-market, 7) 90-day milestones, 8) Why this founder. Use the user's currency (${currency}) for any money. Be concrete and specific. Return ONLY valid JSON, no markdown.`;

    const userPrompt = `Business idea: ${idea.idea_title}
Description: ${idea.description || "(none)"}
Founder profile: ${profile?.full_name || "Founder"}, ${profile?.sector || ""} sector, ${profile?.years_in_service ?? "?"} yrs experience.
Skills: ${Array.isArray(profile?.skills) ? profile.skills.join(", ") : "—"}.
Country: ${country}.`;

    const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${LOVABLE_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [
          { role: "system", content: sysPrompt },
          { role: "user", content: userPrompt },
        ],
        response_format: { type: "json_object" },
      }),
    });

    if (!aiRes.ok) {
      const txt = await aiRes.text();
      console.error("AI gateway error:", aiRes.status, txt);
      if (aiRes.status === 429) return new Response(JSON.stringify({ error: "Rate limited — try again shortly." }), { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      if (aiRes.status === 402) return new Response(JSON.stringify({ error: "AI credits exhausted." }), { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } });
      return new Response(JSON.stringify({ error: "AI service unavailable" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const aiJson = await aiRes.json();
    const content: string = aiJson?.choices?.[0]?.message?.content || "{}";
    let slides: Slide[] = [];
    try {
      const parsed = JSON.parse(content);
      slides = Array.isArray(parsed?.slides) ? parsed.slides : [];
    } catch (e) {
      console.error("Failed to parse AI JSON:", content);
    }
    if (slides.length === 0) {
      return new Response(JSON.stringify({ error: "AI returned no slides — try again." }), {
        status: 502, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const html = buildHtml({
      ideaTitle: idea.idea_title,
      authorName: profile?.full_name || "Founder",
      country,
      currency,
      income: incomeStr,
      slides,
    });

    const path = `${user.id}/${ideaId}-${Date.now()}.html`;
    const { error: upErr } = await admin.storage.from("decks").upload(path, html, {
      contentType: "text/html",
      upsert: true,
    });
    if (upErr) {
      console.error("Upload failed:", upErr);
      return new Response(JSON.stringify({ error: "Failed to save deck" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const { data: pub } = admin.storage.from("decks").getPublicUrl(path);
    const url = pub.publicUrl;

    await authedClient.from("business_ideas").update({ gamma_deck_url: url }).eq("id", ideaId).eq("user_id", user.id);

    return new Response(JSON.stringify({ url, slides: slides.length }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("generate-deck error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
